name: Docker Image CI Swissimages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  schedule:
    - cron: "*/5 * * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env: 
           DOCKER_USER: ${{secrets.DOCKERHUB_SWISSIMAGES_USER}}
           DOCKER_PASSWORD: ${{secrets.DOCKERHUB_SWISSIMAGES_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Docker build
      run: docker build . --file Dockerfile --tag swissimages/baseimage-docker:latest
    
    - name: Docker image push
      run: docker push swissimages/baseimage-docker:latest
